mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 9001
  max-http-header-size: 5242880
############## Sa-Token ?? (??: https://sa-token.cc) ##############
sa-token:
  # token?? (????cookie??)
  token-name: satoken
  # token??????s ??30?, -1??????
  timeout: 2592000
  # token????? (???????????token??) ??: ?
  activity-timeout: -1
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: true
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: true
  # token??
  token-style: uuid
  # ????????
  is-log: false
spring:
    servlet:
      multipart:
        max-file-size: 500MB #???????????
        max-request-size: 2048MB
    jackson: #?????????
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    mvc:
      hiddenmethod:
        filter:
          enabled: true
    datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/orc?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
    http:

      multipart:
        location: /data/upload_tmp