mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 9001
  max-http-header-size: 5242880
############## Sa-Token ?? (??: https://sa-token.cc) ##############
sa-token:
  # token?? (????cookie??)
  token-name: satoken
  # token??????s ??30?, -1??????
  timeout: 2592000
  # token????? (???????????token??) ??: ?
  activity-timeout: -1
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: true
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: true
  # token??
  token-style: uuid
  # ????????
  is-log: false
spring:
    servlet:
      multipart:
        max-file-size: 500MB #???????????
        max-request-size: 2048MB
    jackson: #?????????
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    mvc:
      hiddenmethod:
        filter:
          enabled: true

    datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/offensivefish?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
    http:

      multipart:
        location: /data/upload_tmp
#自定义socketio配置,你可以直接硬编码，看个人喜好
socketio:
  # socketio请求地址
  host: localhost
  # socketio端口
  port: 9999
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  # 连接数大小
  workCount: 100
  # 允许客户请求
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000
  # 命名空间，多个以逗号分隔，
  namespaces: /game,/room,/test
